name: CI Pipeline (Test)

on:
  push:
    branches:
      - prod # Trigger on push to the prod branch
  pull_request:
    branches:
      - prod # Trigger on PR creation against main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use the latest Ubuntu image

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Use the specific version of Node.js for your project

      # Step 3: Install pnpm
      - name: Install pnpm
        run: |
          npm install -g pnpm

      # Step 4: Install dependencies for /web-app using pnpm
      - name: Install dependencies
        run: |
          pnpm install

      # Step 7: Build the app for /web-app
      - name: Build the app
        run: |
          pnpm run build
